// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package access_control

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func AccessControl(body templ.Component) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"ac-tabs\" hx-target=\"#ac-contents\" class=\"m-4 h-full flex flex-col divide-gray-300 divide-y divide-x-0 divide-solid rounded-md bg-gray-100 shadow-md\"><div class=\"flex flex-row gap-2 rounded-t-md p-4\"><div hx-get=\"/access_control/users\" aria-controls=\"tab-content\" aria-selected=\"false\" class=\"tab-pill\" _=\"on htmx:afterRequest take .bg-amber-3 from .tab-pill in the closest parent &lt;div/&gt; set @aria-selected of &lt;[aria-selected=true]/&gt; in the closest parent &lt;div/&gt; to false set my @aria-selected to true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `Users`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div hx-get=\"/access_control/roles\" aria-controls=\"tab-content\" aria-selected=\"false\" class=\"tab-pill\" _=\"on htmx:afterRequest take .bg-amber-3 from .tab-pill in the closest parent &lt;div/&gt; set @aria-selected of &lt;[aria-selected=true]/&gt; in the closest parent &lt;div/&gt; to false set my @aria-selected to true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `Roles`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div hx-get=\"/access_control/permissions\" aria-controls=\"tab-content\" aria-selected=\"true\" class=\"bg-amber-3 tab-pill\" _=\"on htmx:afterRequest take .bg-amber-3 from .tab-pill in the closest parent &lt;div/&gt; set @aria-selected of &lt;[aria-selected=true]/&gt; in the closest parent &lt;div/&gt; to false set my @aria-selected to true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `Permissions`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div id=\"ac-contents\" class=\"flex rounded-b-md p-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = body.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
